name: Wallet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  # Nx Cloud
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

  # Moralis
  moralisApiKey: ${{ secrets.MORALIS_API_KEY }}
  moralisApiSecret: ${{ secrets.MORALIS_API_SECRET }}
  moralisSubdomain: ${{ secrets.MORALIS_SUBDOMAIN }}
  folderPath: ${{ secrets.MORALIS_FOLDERPATH }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Installing...
        run: npm i

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Linting...
        run: |
          npm i
          npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Testing...
        run: |
          npm i
          npm run test

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Building...
        run: |
          npm i
          npm run build

  deploy:
    needs: [lint, test, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Deploying...
        run: |
          npm i
          moralis-admin-cli deploy -p "$env:moralisFolderPath" -d "$env:moralisSubdomain"
