# Documentation
# https://nx.app/docs/configuring-ci
# Tagging: https://github.com/nrwl/nx-tag-successful-ci-run
name: Distributed CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Nx Cloud
  # Requires Github Agents, see more: https://youtu.be/GT7XIwG1i5A?t=222
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

  # Moralis
  moralisApiKey: ${{ secrets.MORALIS_API_KEY }}
  moralisApiSecret: ${{ secrets.MORALIS_API_SECRET }}
  moralisSubdomain: ${{ secrets.MORALIS_SUBDOMAIN }}
  moralisFolderPath: ${{ secrets.MORALIS_FOLDERPATH }}

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=4
      - run: npx nx affected --target=test --parallel --max-parallel=3
      - run: npx nx affected --target=lint --parallel --max-parallel=2
      - run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx affected --target=deploy
      - run: npx nx-cloud stop-all-agents

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=4
      - run: npx nx affected --target=test --parallel --max-parallel=3
      - run: npx nx affected --target=lint --parallel --max-parallel=2
      - run: npx nx-cloud stop-all-agents

  agents:
    runs-on: ubuntu-latest
    name: Nx Agent
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
